# Generated by Django 4.1.4 on 2023-01-23 00:51

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.FileField(upload_to=images.models.generate_filepath),
        ),
    ]
